### PR TITLE
[1.3] refresh to v0.9.1

### PR DESCRIPTION
**Pull request by cdeepali**
## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/open-ce/open-ce/blob/master/CONTRIBUTING.md)?
- [ ] Did you update any affected [documentation](https://github.com/open-ce/open-ce/blob/master/doc/)?
- [ ] Did you write any [tests](https://github.com/open-ce/open-ce/blob/master/tests/) to validate this change?  

## Description

Fixes https://github.com/open-ce/open-ce/issues/265.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) must review and approve.
3. If any  [maintainer](https://github.com/open-ce/open-ce/blob/master/MAINTAINERS.md) requests changes, they must be addressed.

### CODE REVIEW

**Review by dncliss — APPROVED** [review]

**Review by dncliss — APPROVED** [review]

**Comment by tileb1** [comment]
Hello @cdeepali, I'm trying to install torchvision >= 0.9.0 on ppc64le. I built a pytorch env like this
```bash
open-ce build env --python_versions 3.8 --build_types cuda --repository_folder . ./open-ce/envs/pytorch-env.yaml
```
where all the feedstocks are the same as in the master. The build is working fine and is using torchvision 0.8.2. Then I took this PR and edited the torchvision-feedstock repo locally and rebuilt but am getting this error:
```bash
ninja: build stopped: subcommand failed.
    subprocess.run(
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 455, in <module>
    setup(
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 677, in build_extensions
    build_ext.build_extensions(self)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 498, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1257, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1562, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
Traceback (most recent call last):
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/open_ce/build_feedstock.py", line 144, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/conda_build/api.py", line 208, in build
    return build_tree(absolute_recipes, config, stats, build_only=build_only, post=post,
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/conda_build/build.py", line 2334, in build_tree
    packages_from_this = build(metadata, stats,
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/conda_build/build.py", line 1486, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/conda_build/utils.py", line 399, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/lib/python3.8/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/work/conda_build.sh']' returned non-zero exit status 1.
[OPEN-CE-ERROR-11] Unable to build recipe: ./torchvision-feedstock
[OPEN-CE-ERROR-11] Unable to build recipe: torchvision-base
Command '['/bin/bash', '-e', '/users/visics/tlebaill/no_backup/hal/anaconda3/envs/test_build/conda-bld/torchvision-base_1624218846078/work/conda_build.sh']' returned non-zero exit status 1.
```
Do you know how I can fix it? Or what is the easiest way to install a pytorch env with torchvision >= 0.9.0 on ppc64le?
Thanks!

**Comment by cdeepali** [comment]
Yeah actually torchvision `v0.9.0` requires PyTorch `v1.8.0`. However, the latest version of PyTorch available on OpenCE is `v1.7.1` presently. So the build is likely to fail, as you have observed. 

We are working on adding PyTorch v1.8.1 to OpenCE and we will get back to you once that is in.

**Comment by tileb1** [comment]
Hey @cdeepali, thanks for the quick reply! Do you have an ETA for adding for PyTorch v1.8.1 to OpenCE?

**Comment by cdeepali** [comment]
Yes we will have it soon. It may get in a weeks time or so. I will let you know as soon as that happens.

**Review by bnemanich — APPROVED** [review]

**Pull request merged**
